services:
  - type: web
    name: hams-fullstack
    runtime: python
    plan: free
    buildCommand: |
      pip install -r backend/requirements.txt
      npm install --prefix frontend
      npm run build --prefix frontend
    startCommand: gunicorn --chdir backend server.app:app
    envVars:
      - key: STATIC_DIR
        value: /opt/render/project/src/frontend/dist
